/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package org.unitedinternet.cosmo.spi.search.model;

public class _shards {
	private java.lang.Integer successful;

 	public void setSuccessful(java.lang.Integer successful) {
		this.successful = successful;
	}

	public java.lang.Integer getSuccessful() {
		return successful;
	}

	private java.lang.Integer total;

 	public void setTotal(java.lang.Integer total) {
		this.total = total;
	}

	public java.lang.Integer getTotal() {
		return total;
	}

	private java.lang.Integer failed;

 	public void setFailed(java.lang.Integer failed) {
		this.failed = failed;
	}

	public java.lang.Integer getFailed() {
		return failed;
	}

}