/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package org.unitedinternet.cosmo.spi.search.model;


public class _source {

	private java.lang.String uid;

 	public void setUid(java.lang.String uid) {
		this.uid = uid;
	}

	public java.lang.String getUid() {
		return uid;
	}

	private java.lang.String summary;

 	public void setSummary(java.lang.String summary) {
		this.summary = summary;
	}

	public java.lang.String getSummary() {
		return summary;
	}

	

	private java.lang.String location;

 	public void setLocation(java.lang.String location) {
		this.location = location;
	}

	public java.lang.String getLocation() {
		return location;
	}

	

	private java.lang.String description;

 	public void setDescription(java.lang.String description) {
		this.description = description;
	}

	public java.lang.String getDescription() {
		return description;
	}

}