/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package org.unitedinternet.cosmo.spi.search.model;


public class HitElement {
	private _source _source;

 	public void set_source(_source _source) {
		this._source = _source;
	}

	public _source get_source() {
		return _source;
	}

	private java.lang.String _index;

 	public void set_index(java.lang.String _index) {
		this._index = _index;
	}

	public java.lang.String get_index() {
		return _index;
	}

	private java.lang.String _type;

 	public void set_type(java.lang.String _type) {
		this._type = _type;
	}

	public java.lang.String get_type() {
		return _type;
	}

	private java.lang.String _id;

 	public void set_id(java.lang.String _id) {
		this._id = _id;
	}

	public java.lang.String get_id() {
		return _id;
	}

	private java.lang.Double _score;

 	public void set_score(java.lang.Double _score) {
		this._score = _score;
	}

	public java.lang.Double get_score() {
		return _score;
	}

}