/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package org.unitedinternet.cosmo.spi.search.model;

public class Hits {
	private HitElement[] hits;

 	public void setHits(HitElement[] hits) {
		this.hits = hits;
	}

	public HitElement[] getHits() {
		return hits;
	}

	private java.lang.Integer total;

 	public void setTotal(java.lang.Integer total) {
		this.total = total;
	}

	public java.lang.Integer getTotal() {
		return total;
	}

	private java.lang.Double max_score;

 	public void setMax_score(java.lang.Double max_score) {
		this.max_score = max_score;
	}

	public java.lang.Double getMax_score() {
		return max_score;
	}

}