/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package org.unitedinternet.cosmo.spi.search.model;


/**
 * Encapsulates response from Search framework.
 * https://javafromjson.dashingrocket.com/
 * @author izidaru
 *
 */
public class SearchResponse {
	private _shards _shards;

 	public void set_shards(_shards _shards) {
		this._shards = _shards;
	}

	public _shards get_shards() {
		return _shards;
	}

	private java.lang.Integer took;

 	public void setTook(java.lang.Integer took) {
		this.took = took;
	}

	public java.lang.Integer getTook() {
		return took;
	}

	private java.lang.Boolean timed_out;

 	public void setTimed_out(java.lang.Boolean timed_out) {
		this.timed_out = timed_out;
	}

	public java.lang.Boolean getTimed_out() {
		return timed_out;
	}

	private Hits hits;

 	public void setHits(Hits hits) {
		this.hits = hits;
	}

	public Hits getHits() {
		return hits;
	}

}