name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Set up Maven with Java 17
      uses: s4u/setup-maven-action@v1.14.0
      with:
        java-version: '17'
        distribution: 'temurin'
        maven-version: 3.9.4

    - name: Show Maven version
      run: mvn --version

    - name: Build with Maven
      run: mvn -B package --file pom.xml